development:
  base_url: http://localhost
  email_to: 'nvinet@gmail.com'
  booking_email_to: 'nvinet@gmail.com'
  paypal_url: 'https://www.sandbox.paypal.com/cgi-bin/webscr'
  paypal_email: 'info@riadyamina.com'

production:
  base_url: http://www.riadyamina.com
  email_to: 'info@riadyamina.com'
  booking_email_to: 'info@riadyamina.com'
  paypal_url: 'https://www.paypal.com/cgi-bin/webscr'
  paypal_email: 'info@riadyamina.com'